################################################################################
#  DRINKS                                                                      #
################################################################################
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drinks-v1
  labels:
    app: drinks
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drinks
      version: v1
  template:
    metadata:
      labels:
        app: drinks
        version: v1
    spec:
      containers:
        - name: drinks
          image: drinks-microservice:1.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
