################################################################################
#  ROUTER                                                                      #
################################################################################
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-v2
  labels:
    app: router
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: router
      version: v2
  template:
    metadata:
      labels:
        app: router
        version: v2
    spec:
      containers:
        - name: router
          image: router-microservice:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4002
