################################################################################
#  DRINKS                                                                      #
################################################################################
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: drinks-v2
  labels:
    app: drinks
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drinks
      version: v2
  template:
    metadata:
      labels:
        app: drinks
        version: v2
    spec:
      containers:
        - name: drinks
          image: drinks-microservice:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
