################################################################################
#  FRONTEND                                                                    #
################################################################################
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
  labels:
    app: frontend
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      version: v2
  template:
    metadata:
      labels:
        app: frontend
        version: v2
    spec:
      containers:
        - name: frontend
          image: frontend-microservice:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4005
