################################################################################
#  GATEAWAY                                                                    #
################################################################################

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: services-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---


################################################################################
#  VIRTUAL SERVICE - FRONTEND                                                  #
################################################################################
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
    - "*"
  gateways:
    - services-gateway
  http:
    - match:
        - uri:
            exact: /
      route:
        - destination:
            host: frontend
            port:
              number: 4005


################################################################################
#  VIRTUAL SERVICE - ROUTER                                                    #
################################################################################
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: router
spec:
  hosts:
    - "*"
  gateways:
    - services-gateway
  http:
    - match:
        - uri:
            prefix: /drinks
        - uri:
            prefix: /cracks
      route:
        - destination:
            host: router
            port:
              number: 4002


