apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: router
spec:
  hosts:
    - "*"
  gateways:
    - services-gateway
  http:
    - match:
        - uri:
            exact: /drinks
      route:
        - destination:
            host: router
            port:
              number: 4005
---

