################################################################################
#  MARIADB                                                                       #
################################################################################
---

### Secret
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: kubernetes.io/basic-auth
stringData:
  password: password
  database: drinksdb

---

### Service
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
    service: mariadb
spec:
  ports:
    - port: 3306
      name: tcp
  selector:
    app: mariadb

---

### Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadbdata-pv-volumen
  labels:
    type: local
    app: mariadb
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/mariadb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadbdata-pv-claim
  labels:
    app: mariadb
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      version: v1
  template:
    metadata:
      labels:
        app: mariadb
        version: v1
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
            - name: MARIADB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: database
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mariadb
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadbdata-pv-claim
