################################################################################
#  MONGO                                                                       #
################################################################################
---

### Secret
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: kubernetes.io/basic-auth
stringData:
  database: cracksdb
  password: Password123!
  username: root

---

### Service
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
    service: mongo
spec:
  ports:
    - port: 27017
      name: tcp
  selector:
    app: mongo

---

### Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodata-pv-volumen
  labels:
    type: local
    app: mongo
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodata-pv-claim
  labels:
    app: mongo
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---

### Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
      version: v1
  template:
    metadata:
      labels:
        app: mongo
        version: v1
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: database
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /var/lib/mongo
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongodata-pv-claim
