################################################################################
#  DRINKS                                                                      #
################################################################################
---

### Service
apiVersion: v1
kind: Service
metadata:
  name: drinks
  labels:
    app: drinks
    service: drinks
spec:
  ports:
    - port: 4000
      name: http
  selector:
    app: drinks

