################################################################################
#  FRONTEND                                                                    #
################################################################################
---

### Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
spec:
  ports:
    - port: 4005
      name: http
  selector:
    app: frontend

