################################################################################
#  ROUTER                                                                      #
################################################################################
---

### Service
apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    app: router
    service: router
spec:
  ports:
    - port: 4002
      name: http
  selector:
    app: router

