################################################################################
#  CRACKS                                                                      #
################################################################################
---

### Service
apiVersion: v1
kind: Service
metadata:
  name: cracks
  labels:
    app: cracks
    service: cracks
spec:
  ports:
    - port: 4001
      name: http
  selector:
    app: cracks

